services:
  postgres:
    image: postgres:16
    container_name: mini-projet-s6-postgres
    environment:
      POSTGRES_DB: mini_projet_s6
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
