<?php
/**
 * Formulaire categorie (create/edit)
 */
$isEdit = ($mode ?? 'create') === 'edit';
$form = $categoryForm ?? [];
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><?= $isEdit ? 'Modifier' : 'Nouvelle' ?> categorie - BackOffice</title>
  <meta name="robots" content="noindex, nofollow" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = { theme: { extend: { fontFamily: { sans: ['Plus Jakarta Sans', 'sans-serif'] }, boxShadow: { soft: '0 10px 30px rgba(15, 23, 42, 0.08)' } } } };
  </script>
</head>
<body class="min-h-screen bg-slate-50 font-sans text-slate-800">
<div class="flex min-h-screen">
  <?php include __DIR__ . '/../includes/admin_sidebar.php'; ?>

  <div class="w-full xl:ml-72">
    <?php include __DIR__ . '/../includes/admin_header.php'; ?>

    <main class="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8">
      <div class="mb-6">
        <h1 class="text-3xl font-bold tracking-tight text-slate-900"><?= $isEdit ? 'Modifier' : 'Creer' ?> une categorie</h1>
        <p class="mt-2 text-sm text-slate-600">Definissez une categorie claire pour structurer la publication.</p>
      </div>

      <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft">
        <form action="<?= $isEdit ? url('categories/' . $categoryId) : url('categories') ?>" method="post" class="space-y-5">

          <?php if (!empty($errors)): ?>
            <div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">
              <ul class="list-disc pl-4">
                <?php foreach ($errors as $error): ?>
                  <li><?= e($error) ?></li>
                <?php endforeach; ?>
              </ul>
            </div>
          <?php endif; ?>

          <div>
            <label class="mb-2 block text-sm font-semibold text-slate-700" for="nom">Nom</label>
            <input type="text" name="nom" id="nom" maxlength="100" value="<?= e($form['nom'] ?? '') ?>" class="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none transition focus:border-blue-300 focus:bg-white" required />
          </div>

          <div>
            <label class="mb-2 block text-sm font-semibold text-slate-700" for="slug">Slug</label>
            <input type="text" name="slug" id="slug" maxlength="110" value="<?= e($form['slug'] ?? '') ?>" class="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none transition focus:border-blue-300 focus:bg-white" required />
            <p class="mt-1 text-xs text-slate-500">Exemple: diplomatie</p>
          </div>

          <div>
            <label class="mb-2 block text-sm font-semibold text-slate-700" for="description">Description</label>
            <textarea name="description" id="description" rows="4" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none transition focus:border-blue-300 focus:bg-white"><?= e($form['description'] ?? '') ?></textarea>
          </div>

          <div class="flex flex-wrap gap-3 pt-2">
            <button type="submit" class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-700">Enregistrer</button>
            <a href="<?= url('categories') ?>" class="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-50">Annuler</a>
          </div>
        </form>
      </section>
    </main>
  </div>
</div>

<script>
  const nomInput = document.getElementById('nom');
  const slugInput = document.getElementById('slug');

  if (nomInput && slugInput) {
    nomInput.addEventListener('input', function() {
      if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
        const slug = this.value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
        slugInput.value = slug;
        slugInput.dataset.autoGenerated = 'true';
      }
    });
    slugInput.addEventListener('input', function() { this.dataset.autoGenerated = 'false'; });
  }
</script>
</body>
</html>
