<?php
/**
 * Formulaire categorie (create/edit)
 */
$isEdit = ($mode ?? 'create') === 'edit';
$form = $categoryForm ?? [];
?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><?= $isEdit ? 'Modifier' : 'Nouvelle' ?> categorie - BackOffice</title>
  <meta name="description" content="Formulaire backoffice pour creer ou modifier une categorie Iran War News." />
  <meta name="keywords" content="formulaire categorie, administration, iran war news" />
  <meta name="robots" content="noindex, nofollow" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = { theme: { extend: { fontFamily: { sans: ['Plus Jakarta Sans', 'sans-serif'] }, boxShadow: { soft: '0 10px 30px rgba(15, 23, 42, 0.08)' } } } };
  </script>
</head>
<body class="min-h-screen bg-slate-50 font-sans text-slate-800">
<div class="flex min-h-screen">
  <?php include __DIR__ . '/../includes/admin_sidebar.php'; ?>

  <div class="w-full xl:ml-72">
    <?php
    $adminHeaderMode = 'simple';
    $adminSearchPlaceholder = 'Rechercher...';
    $adminHeaderButtons = [
      ['href' => url('logout'), 'label' => 'Deconnexion', 'class' => 'rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50'],
    ];
    include __DIR__ . '/../includes/admin_header.php';
    ?>

    <main class="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8">
      <div class="mb-6">
        <h1 class="text-3xl font-bold tracking-tight text-slate-900"><?= $isEdit ? 'Modifier' : 'Creer' ?> une categorie</h1>
        <p class="mt-2 text-sm text-slate-600">Definissez une categorie claire pour structurer la publication.</p>
      </div>

      <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft">
        <form action="<?= $isEdit ? url('categories/' . $categoryId) : url('categories') ?>" method="post" class="space-y-5">
          <?php require __DIR__ . '/_fields.php'; ?>
        </form>
      </section>
    </main>
  </div>
</div>

<script>
  const nomInput = document.getElementById('nom');
  const slugInput = document.getElementById('slug');

  if (nomInput && slugInput) {
    nomInput.addEventListener('input', function() {
      if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
        const slug = this.value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
        slugInput.value = slug;
        slugInput.dataset.autoGenerated = 'true';
      }
    });
    slugInput.addEventListener('input', function() { this.dataset.autoGenerated = 'false'; });
  }
</script>
</body>
</html>
